W6
vlasenckov/MIPT_py_3_term pull request #7
Opened 2020-10-20 20:09 UTC by vlasenckov

2020-10-21 21:03 UTC, alekseik1 requested changes
Пожалуйста, форматируй вывод. Я не мог понять ничего, что выводит программа, пока не вчитался в код.

Также есть много комментариев по коду.

2020-10-21 21:03 UTC, alekseik1 commented on w6/my_math.py
> +    print("sinus work:\n for complex: {}\n for real: {}\n".
sine, не sinus

2020-10-21 21:03 UTC, alekseik1 commented on w6/my_math.py
> +          format(complex_number.sin(2 * MyMath.pi),
А синус от мнимого подсчитает?)))

2020-10-21 21:03 UTC, alekseik1 commented on w6/my_math.py
> +        neg_comp_sqrt = MyComplexMath.sqrt(-10)
Не клади много кода в `try`.

Если вылетит ошибка (сейчас оно так и происходит при запуске), то нельзя точно сказать, какая строка ее вызвала. Может, это `MyComplexMath.sqrt(10)` упал, а может, и другое

2020-10-21 21:03 UTC, alekseik1 commented on w6/my_complex.py
> +        return instance.__dict__[self.__name]
Что это делает? О_о

2020-10-21 21:03 UTC, alekseik1 commented on w6/my_complex.py
> +        return round(self.real)
очень странно, конечно, определять `int` для комплексного числа с математической точки зрения

2020-10-21 21:03 UTC, alekseik1 commented on w6/my_complex.py
> +        return self.real
и здесь тоже

2020-10-21 21:03 UTC, alekseik1 commented on w6/my_complex.py
> +    def __lt__(self, other) -> bool:
на множестве комплексных чисел нет операций `<`, `>`. Поэтому это математически некорректно.

Но у нас курс не про математику, так что хорошо, что ты разобрался с `__lt__`, `__ge__`

2020-10-21 21:03 UTC, alekseik1 commented on w6/my_complex.py
> +    def __ge__(self, other) -> bool:
Для консистентности можно было бы еще `__gt__` определить

2020-10-21 21:03 UTC, alekseik1 commented on w6/my_complex.py
> +        return self.real * other.real + self.imag + other.imag
`-self.imag*other.imag` забыл. И это еще должно быть комплексное число

2020-10-21 21:03 UTC, alekseik1 commented on w6/my_complex.py
> +        return hash(id(self))
круто, после такого твои числа могут быть ключами в словаре.

Но лучше брать хэш от, условно, кортежа `(real, imaginary)`. 
В текущем подходе есть проблема: если ты объявишь
```python
a = MyComplex(1, 1)
b = MyComplex(1, 1)
```
то увидишь, что хэш от них будет разный (т.к. они занимают разное место в памяти). Соответственно, при использовании их в качестве ключа в словаре ты увидишь неприятный феномен - два одинаковых комплексных числа вполне сосуществуют как ключи в словаре

2020-10-21 21:03 UTC, alekseik1 commented on w6/my_vector.py
> +                raise ValueError("vector from 0-dimensional space must be zero-vector")
да можно было бы и просто игнорировать второй аргумент. Но это дело вкуса

2020-10-21 21:03 UTC, alekseik1 commented on w6/my_vector.py
> +            string += str(self.__args[i]) + ', '
это **очень** плохая практика складывать строки в питоне. Напишу один раз, дальше буду ставить 0 за все задание, если такое увижу.

Пусть у тебя `self.__args` имеет длину N. Поскольку строки в питоне неизменяемы, на каждой итериции у тебя будет (а) создаваться новая строка, (б) посимвольно копироваться старая строка в новую, затем посимвольно добавляться вторая строка-операнд.

Соответственно, на первой итерации будет `len(self.__args[0])` копирований + добавление `', '`.
На второй уже `len(self.__args[0]) + len(', ') + len(self.__args[1])` копирований + добавление `', '`.
Это образует арифметическую прогрессию, и суммарно у тебя получается O(N^2) операций (по формулы для суммы) просто на пустом месте.

Такая сложность может сильно замедлить программу на больших данных

2020-10-21 21:03 UTC, alekseik1 commented on w6/my_vector.py
> +            string += str(self.__args[i]) + ', '
Используй `', '.join(self.__args)` - это даст O(N)

2020-10-21 21:03 UTC, alekseik1 commented on w6/my_vector.py
> +            string += str(self.__args[i]) + ', '
Такая же история, что выше

2020-10-21 21:03 UTC, alekseik1 commented on w6/my_vector.py
> +        self.__args +=  other.__args
кажется, пробел лишний

2020-10-21 21:03 UTC, alekseik1 commented on w6/my_vector.py
> +    def __and__(self, other) -> 'MyVector':
Ты уверен, что это правильный type annotation для возвращаемого значения?

2020-10-21 21:03 UTC, alekseik1 commented on w6/my_vector.py
> +    print(vector_1 & vector_2)
А, точно. Обычно через `&` обозначают векторное произведение. Для скалярного оставляют `*`

2020-10-24 18:44 UTC, vlasenckov commented on w6/my_vector.py
> +            string += str(self.__args[i]) + ', '
Эхх, точно, это у меня просто флэшбэк из плюсов был: там вроде такая практика никаких новых переменных не создает.

2020-10-24 18:45 UTC, vlasenckov commented
@alekseik1 Пофиксил все, что вы отметили.

2020-10-25 15:08 UTC, alekseik1 requested changes
Нет оператора `-a` для вектора

2020-10-25 15:08 UTC, alekseik1 commented on w6/my_math.py
> +        print("positive real sqrt: ", pos_real_sqrt)
Опять много кода в `try/except`

2020-10-25 15:08 UTC, alekseik1 commented on w6/my_math.py
> +        print("negative real sqrt: ", neg_real_sqrt)
Много кода в `try/except`

2020-10-26 11:39 UTC, vlasenckov commented
@alekseik1, поправил.

2020-10-26 18:54 UTC, alekseik1 approved these changes
Теперь порядок. 16/16

2020-10-26 18:54 UTC, merged